window.TWEETY_LEVELS = [
  {
    "id": 1,
    "name": "Sleepy Twilight",
    "rows": 6,
    "density": 0.72,
    "pressure": 0.38,
    "stompEvery": 8,
    "stomp": 7,
    "helperInterval": 48,
    "hatchChance": 0.09,
    "helperFirst": 40,
    "helperJitter": 6,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  },
  {
    "id": 2,
    "name": "Moonlit Steps",
    "rows": 7,
    "density": 0.82,
    "pressure": 0.82,
    "stompEvery": 5,
    "stomp": 11,
    "helperInterval": 44,
    "hatchChance": 0.13,
    "helperFirst": 37,
    "helperJitter": 6,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  },
  {
    "id": 3,
    "name": "Indigo Garden",
    "rows": 7,
    "density": 0.8,
    "pressure": 0.95,
    "stompEvery": 5,
    "stomp": 11,
    "helperInterval": 40,
    "hatchChance": 0.13,
    "helperFirst": 34,
    "helperJitter": 5,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  },
  {
    "id": 4,
    "name": "Velvet Arches",
    "rows": 7,
    "density": 0.82,
    "pressure": 1.1,
    "stompEvery": 5,
    "stomp": 11,
    "helperInterval": 34,
    "hatchChance": 0.13,
    "helperFirst": 29,
    "helperJitter": 5,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  },
  {
    "id": 5,
    "name": "Starlight Pockets",
    "rows": 8,
    "density": 0.83,
    "pressure": 1.3,
    "stompEvery": 5,
    "stomp": 12,
    "helperInterval": 34,
    "hatchChance": 0.13,
    "helperFirst": 29,
    "helperJitter": 5,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  },
  {
    "id": 6,
    "name": "Midnight Windows",
    "rows": 8,
    "density": 0.84,
    "pressure": 1.5,
    "stompEvery": 5,
    "stomp": 12,
    "helperInterval": 34,
    "hatchChance": 0.13,
    "helperFirst": 29,
    "helperJitter": 5,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  },
  {
    "id": 7,
    "name": "Violet Cascade",
    "rows": 8,
    "density": 0.84,
    "pressure": 1.7,
    "stompEvery": 5,
    "stomp": 13,
    "helperInterval": 34,
    "hatchChance": 0.13,
    "helperFirst": 29,
    "helperJitter": 5,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  },
  {
    "id": 8,
    "name": "Moonstone Maze",
    "rows": 9,
    "density": 0.85,
    "pressure": 1.9,
    "stompEvery": 4,
    "stomp": 13,
    "helperInterval": 34,
    "hatchChance": 0.13,
    "helperFirst": 29,
    "helperJitter": 5,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  },
  {
    "id": 9,
    "name": "Comet Crossing",
    "rows": 9,
    "density": 0.85,
    "pressure": 2.15,
    "stompEvery": 4,
    "stomp": 14,
    "helperInterval": 34,
    "hatchChance": 0.13,
    "helperFirst": 29,
    "helperJitter": 5,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  },
  {
    "id": 10,
    "name": "Nightfall Rush",
    "rows": 9,
    "density": 0.86,
    "pressure": 2.4,
    "stompEvery": 4,
    "stomp": 14,
    "helperInterval": 34,
    "hatchChance": 0.13,
    "helperFirst": 29,
    "helperJitter": 5,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  },
  {
    "id": 11,
    "name": "Last Moonrise",
    "rows": 10,
    "density": 0.86,
    "pressure": 2.65,
    "stompEvery": 4,
    "stomp": 15,
    "helperInterval": 34,
    "hatchChance": 0.13,
    "helperFirst": 29,
    "helperJitter": 5,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  },
  {
    "id": 12,
    "name": "Tweety Takes Over",
    "rows": 10,
    "density": 0.86,
    "pressure": 2.9,
    "stompEvery": 4,
    "stomp": 15,
    "helperInterval": 34,
    "hatchChance": 0.13,
    "helperFirst": 29,
    "helperJitter": 5,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  },
  {
    "id": 13,
    "name": "Beyond Moonrise",
    "rows": 10,
    "density": 0.87,
    "pressure": 3.12,
    "stompEvery": 4,
    "stomp": 15,
    "helperInterval": 34,
    "hatchChance": 0.13,
    "helperFirst": 29,
    "helperJitter": 5,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  },
  {
    "id": 14,
    "name": "Twilight Summit",
    "rows": 10,
    "density": 0.88,
    "pressure": 3.48,
    "stompEvery": 4,
    "stomp": 16,
    "helperInterval": 34,
    "hatchChance": 0.13,
    "helperFirst": 29,
    "helperJitter": 5,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  },
  {
    "id": 15,
    "name": "Final Challenge",
    "rows": 10,
    "density": 0.89,
    "pressure": 3.8,
    "stompEvery": 3,
    "stomp": 16,
    "helperInterval": 34,
    "hatchChance": 0.13,
    "helperFirst": 29,
    "helperJitter": 5,
    "helperGap": 26,
    "helperSuccessGap": 36,
    "helperDangerStart": 430,
    "helperDangerFull": 535,
    "helperChanceLow": 0.12,
    "helperChanceHigh": 0.72,
    "helperRetry": 6
  }
];
