window.TWEETY_LEVELS = [
  {
    "id": 1,
    "name": "Sleepy Twilight",
    "rows": 6,
    "density": 0.72,
    "pressure": 0.38,
    "stompEvery": 8,
    "stomp": 7,
    "helperInterval": 48,
    "hatchChance": 0.09,
    "helperFirst": 40,
    "helperJitter": 6,
    "helperGap": 12
  },
  {
    "id": 2,
    "name": "Moonlit Steps",
    "rows": 7,
    "density": 0.82,
    "pressure": 0.82,
    "stompEvery": 5,
    "stomp": 11,
    "helperInterval": 44,
    "hatchChance": 0.13,
    "helperFirst": 37,
    "helperJitter": 6,
    "helperGap": 12
  },
  {
    "id": 3,
    "name": "Indigo Garden",
    "rows": 7,
    "density": 0.8,
    "pressure": 0.95,
    "stompEvery": 5,
    "stomp": 11,
    "helperInterval": 40,
    "hatchChance": 0.13,
    "helperFirst": 34,
    "helperJitter": 5,
    "helperGap": 11
  },
  {
    "id": 4,
    "name": "Velvet Arches",
    "rows": 7,
    "density": 0.82,
    "pressure": 1.1,
    "stompEvery": 5,
    "stomp": 11,
    "helperInterval": 34,
    "hatchChance": 0.13,
    "helperFirst": 29,
    "helperJitter": 5,
    "helperGap": 10
  },
  {
    "id": 5,
    "name": "Starlight Pockets",
    "rows": 8,
    "density": 0.83,
    "pressure": 1.3,
    "stompEvery": 5,
    "stomp": 12,
    "helperInterval": 29,
    "hatchChance": 0.13,
    "helperFirst": 25,
    "helperJitter": 4,
    "helperGap": 9
  },
  {
    "id": 6,
    "name": "Midnight Windows",
    "rows": 8,
    "density": 0.84,
    "pressure": 1.5,
    "stompEvery": 5,
    "stomp": 12,
    "helperInterval": 25,
    "hatchChance": 0.13,
    "helperFirst": 22,
    "helperJitter": 4,
    "helperGap": 8
  },
  {
    "id": 7,
    "name": "Violet Cascade",
    "rows": 8,
    "density": 0.84,
    "pressure": 1.7,
    "stompEvery": 5,
    "stomp": 13,
    "helperInterval": 22,
    "hatchChance": 0.13,
    "helperFirst": 19,
    "helperJitter": 3,
    "helperGap": 7
  },
  {
    "id": 8,
    "name": "Moonstone Maze",
    "rows": 9,
    "density": 0.85,
    "pressure": 1.9,
    "stompEvery": 4,
    "stomp": 13,
    "helperInterval": 19,
    "hatchChance": 0.13,
    "helperFirst": 17,
    "helperJitter": 3,
    "helperGap": 6
  },
  {
    "id": 9,
    "name": "Comet Crossing",
    "rows": 9,
    "density": 0.85,
    "pressure": 2.15,
    "stompEvery": 4,
    "stomp": 14,
    "helperInterval": 16,
    "hatchChance": 0.13,
    "helperFirst": 14,
    "helperJitter": 2,
    "helperGap": 6
  },
  {
    "id": 10,
    "name": "Nightfall Rush",
    "rows": 9,
    "density": 0.86,
    "pressure": 2.4,
    "stompEvery": 4,
    "stomp": 14,
    "helperInterval": 16,
    "hatchChance": 0.13,
    "helperFirst": 14,
    "helperJitter": 2,
    "helperGap": 6
  },
  {
    "id": 11,
    "name": "Last Moonrise",
    "rows": 10,
    "density": 0.86,
    "pressure": 2.65,
    "stompEvery": 4,
    "stomp": 15,
    "helperInterval": 15,
    "hatchChance": 0.13,
    "helperFirst": 14,
    "helperJitter": 2,
    "helperGap": 6
  },
  {
    "id": 12,
    "name": "Tweety Takes Over",
    "rows": 10,
    "density": 0.86,
    "pressure": 2.9,
    "stompEvery": 4,
    "stomp": 15,
    "helperInterval": 15,
    "hatchChance": 0.13,
    "helperFirst": 14,
    "helperJitter": 2,
    "helperGap": 6
  }
];
